version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-teampolls}
      REDIS_URL: redis://${REDIS_USER:-redis}:${REDIS_PASSWORD:-}@redis:6379/0
      JWT_SECRET: ${JWT_SECRET:-fallback-secret-for-dev}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app # For development, mount code changes
    command: sh -c "echo \"Forcing migrations with explicit input...\" && pg-migrate up -u 'postgresql://poll_admin:secure123@db:5432/teampolls_db' -d /app/migrations --verbose 2>&1 && echo \"Migrations finished.\" && npm start"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-teampolls}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: